
patient2 = Patient.create!({:name => 'Patient 1', :phone => '9452919', :email => 'patient1@patient1.com', :diagnosis => 'diabetes', :user_id => 1})
# Test.create!({:name =>'HBA1C'})
# Test.create!({:name =>'Test 2'})
# Test.create!({:name =>'Test 3'})
# Test.create!({:name =>'Test 4'})
Medication.create!({:name => 'Panadol'})
Medication.create!({:name => 'Dhamotil'})
Medication.create!({:name => 'AntiBiotics'})
Medication.create!({:name => 'Diabetes Test kit'})
Medication.create!({:name => 'Arcoxia'})
Appt.create!({:patient_id => 1, :time => '2019-12-06T10:00:00+08:00'})
MedicationPatient.create!({:medication_id => 1, :patient_id => 1})
MedicationPatient.create!({:medication_id => 2, :patient_id => 1})
ApptTest.create!({:appt_id => 1, :test_id => 1})
